---
- name: Reboot
  ansible.builtin.reboot:

- name: Reboot if necessary
  ansible.builtin.reboot:
  when: reboot_required.stat.exists

- name: Restart global hostapd systemd service
  ansible.builtin.systemd:
    name: hostapd
    state: restarted
    enabled: true

- name: Enable global systemd-networkd systemd service
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
