---
- name: Full system update
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    autoclean: true
    autoremove: true
  notify: Reboot if required

- name: Check if reboot is needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Disable cron e-mail notifications
  ansible.builtin.cron:
    name: MAILTO
    user: root
    env: true
    job: ""

- name: Allow all handlers to run
  ansible.builtin.meta: flush_handlers
