---
- name: Install essential packages for unatended upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
    state: present

- name: Copy unattended-upgrades configuration files in place
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/apt/apt.conf.d/{{ item }}
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
