---
#
# Ansible
#

ssh_key: ~/.ssh/id_ed25519

#
# MSMTP (chriswayg.msmtp-mailer)
#

msmtp_accounts:
  - account: ickule
    host: "{{ email_smtp_host }}"
    port: "{{ email_smtp_port_startls }}"
    auth: "on"
    from: "{{ email }}"
    user: "{{ email }}"
    password: "{{ email_password }}"

msmtp_default_account: ickule

msmtp_alias_default: "{{ email }}"

#
# SSH security (geerlingguy.security)
#

security_sudoers_passwordless: ["{{ username }}"]
security_autoupdate_enabled: false # Will handle manually

#
# Unattended upgrades
#

autoupdate_reboot: true
autoupdate_mail_to: "{{ email }}"
autoupdate_reboot_time: 03:00
autoupdate_mail_report: always # Could be "always", "on-change" or "only-on-error"
